- name: Create remote working dir
  file:
    path: "{{ working_dir }}"
    state: directory

- name: Generate ssh keys
  delegate_to: localhost
  command: >
    ssh-keygen -f '{{ item.path }}' -N ''
    -C '{{ item.comment }}'
    -t rsa -b 4096
  args:
    creates: "{{ item.path }}"
  with_items:
    - path: "{{ virt_power_key }}"
      comment: "ansible_generated_virt_power"
    - path: "{{ undercloud_key }}"
      comment: "ansible_generated_undercloud"

- name: Read virt_power private key
  set_fact:
    virt_power_key_pvt: "{{ item }}"
  with_file:
    - "{{ virt_power_key }}"

- name: add virt_power_key to remote authorized_keys
  authorized_key:
    user: "{{ ansible_user_id }}"
    key: "{{ item }}"
    manage_dir: true
  with_file:
    - "{{ virt_power_key }}.pub"
