# LKS: should this be parameterized? E.g., if we wanted something other than 
# liberty on the undercloud...
- name: install release repo
  yum:
    name: http://rdoproject.org/repos/openstack-liberty/rdo-release-liberty.rpm
    state: present
  become: true

- name: ensure libvirt and other deps are installed
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - qemu-kvm
    - libvirt
    - libvirt-python
    - python-lxml
    - openvswitch
  become: true

- name: start openvswitch
  service:
    name: openvswitch
    state: started
    enabled: true
  become: true

- include: configure_kvm.yml

- name: start libvirtd
  service:
    name: libvirtd
    state: running
    enabled: true
  become: true
