# Fetching the undercloud images can take a long time.  This
# tasklist caches images in {{ image_cache_dir }} if an image is
# (a) downloaded successfully and (b) successfully verifies against
# the checksum.  Images are cached using the checksum as the filename,
# and subsequent playbook runs will use the cached copy rather than
# trying to fetch the remote copy.

- name: Ensure image cache directory exists
  file:
    path: "{{ image_cache_dir }}"
    state: directory

- name: Get undercloud image expected checksum
  command: >
    curl --trace-ascii /dev/stderr -sf {{ image_url }}.md5
  register: undercloud_md5_expected

- name: Check for undercloud image in cache
  command: >
    test -f {{undercloud_md5_expected.stdout.split()[0]}}.qcow2
  args:
    chdir: "{{ image_cache_dir }}"
  ignore_errors: true
  register: image_exists
  changed_when: false

- name: Get undercloud image
  command: >
    curl -sf -C- -o _undercloud.qcow2 {{ image_url }}
  args:
    chdir: "{{ image_cache_dir }}"
  register: curl_result
  until: curl_result.rc not in [18, 56]
  retries: 20
  delay: 5
  when: image_exists|failed

- name: Get actual md5 checksum of undercloud image
  command: >
    md5sum _undercloud.qcow2
  args:
    chdir: "{{ image_cache_dir }}"
  register: undercloud_md5_actual
  when: image_exists|failed

- name: Verify undercloud image checksum
  fail:
    msg: undercloud image checksum does not match
  when: >
    image_exists|failed and (
    undercloud_md5_expected.stdout.split()[0] !=
    undercloud_md5_actual.stdout.split()[0])

- name: Cache undercloud image by checksum
  command: >
    mv _undercloud.qcow2 {{ undercloud_md5_expected.stdout.split()[0] }}.qcow2
  args:
    chdir: "{{ image_cache_dir }}"
  when: image_exists|failed

- name: Get undercloud image from cache
  command:
    cp {{ image_cache_dir }}/{{undercloud_md5_expected.stdout.split()[0]}}.qcow2
    {{ working_dir }}/undercloud.qcow2
