- name: Remove virt_power_key from remote authorized_keys
  authorized_key:
    user: "{{ ansible_user_id }}"
    state: absent
    key: "{{ item }}"
    manage_dir: true
  with_file:
    - "{{ virt_power_key }}.pub"
  ignore_errors: true
