# NB: We use "virsh" here instead of the "virt" module because
# these tasks may be called before the dependencies of the "virt"
# module are satisfied.

- name: Check if libvirt is available
  command: >
    virsh uri
  ignore_errors: true
  register: libvirt_check
  become: true

- name: Check overcloud vms
  command: >
    virsh domid "{{ item.name }}"
  with_items: "{{ overcloud_nodes }}"
  ignore_errors: true
  register: overcloud_check
  become: true

- name: Destroy overcloud vms
  command:
    virsh destroy "{{ item.item.name }}"
  when: item|success
  with_items: "{{ overcloud_check.results }}"
  ignore_errors: true
  become: true

- name: Undefine overcloud vms
  command:
    virsh undefine "{{ item.item.name }}"
  when: item|success
  with_items: "{{ overcloud_check.results }}"
  become: true

- name: Check undercloud vm
  command: >
    virsh domid "{{ item.name }}"
  with_items: "{{ undercloud_nodes }}"
  ignore_errors: true
  register: undercloud_check
  become: true

- name: Destroy undercloud vm
  command: >
    virsh destroy "{{ item.item.name }}"
  when: item|success
  with_items: "{{ undercloud_check.results }}"
  ignore_errors: true
  become: true

- name: Undefine undercloud vm
  command: >
    virsh undefine "{{ item.item.name }}"
  when: item|success
  with_items: "{{ undercloud_check.results }}"
  become: true

# the virsh vol-dumpxml ... > /dev/null is here (and elsewhere) due to
# https://bugzilla.redhat.com/show_bug.cgi?id=1293804
- name: Delete baremetal vm storage
  shell: |
    virsh vol-dumpxml --pool '{{ vms.volume_pool }}' \
      '{{ item.name }}'.qcow2 2>&1 > /dev/null
    virsh vol-delete --pool '{{ vms.volume_pool }}' \
      '{{ item.name }}'.qcow2
  with_items: "{{ overcloud_nodes }}"
  ignore_errors: true
  become: true

- name: Delete undercloud vm storage
  shell: |
    virsh vol-dumpxml --pool '{{ vms.volume_pool }}' \
      '{{ item.name }}'.qcow2 2>&1 > /dev/null
    virsh vol-delete --pool '{{ vms.volume_pool }}' \
      '{{ item.name }}'.qcow2
  with_items: "{{ undercloud_nodes }}"
  ignore_errors: true
  become: true
